import os
import sqlite3
import json
from datetime import datetime
from flask import Flask, request, jsonify
from dotenv import load_dotenv
from stylometry import compute_stylometry_score
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

load_dotenv()

GROQ_API_KEY = os.getenv("GROQ_API_KEY")

DB_PATH = os.path.join(os.path.dirname(__file__), "audit.db")

app = Flask(__name__)

# Rate limiter: default per-IP plus per-creator limits on submit
limiter = Limiter(key_func=get_remote_address, default_limits=["60 per hour"])
limiter.init_app(app)

def get_request_data():
    if request.is_json:
        return request.get_json(silent=True) or {}
    if request.form:
        return request.form.to_dict()
    return {}


def creator_key():
    # Use creator_id as rate limit key when available, otherwise fallback to IP
    try:
        data = get_request_data()
        creator = data.get("creator_id")
        if creator:
            return f"creator:{creator}"
    except Exception:
        pass
    return get_remote_address()


def init_db():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute(
        """
        CREATE TABLE IF NOT EXISTS audit (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT,
            content_id TEXT,
            creator_id TEXT,
            result TEXT,
            confidence REAL,
            signals_json TEXT,
            label_text TEXT,
            notes TEXT
        )
        """
    )
    c.execute(
        """
        CREATE TABLE IF NOT EXISTS appeals (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT,
            content_id TEXT,
            creator_id TEXT,
            reason TEXT,
            status TEXT,
            linked_audit_id INTEGER
        )
        """
    )
    conn.commit()
    conn.close()

init_db()

def call_groq_stub(text):
    """Return score in [0,1] where 1 = AI-generated using formal/casual marker heuristic."""
    if not GROQ_API_KEY:
        formal_markers = [
            "paradigm", "essential", "stakeholders", "collaborate", "important to note",
            "furthermore", "transformative", "implications", "mandate", "unintended consequences",
            "extensive", "literature", "tension", "valuations"
        ]
        casual_markers = ["ok so", "honestly", "lol", "imo", "ngl", "anyway", "kinda", "sorta"]
        
        text_lower = text.lower()
        formal_score = sum(1 for m in formal_markers if m in text_lower) / max(1, len(text_lower.split()) / 50)
        casual_score = sum(1 for m in casual_markers if m in text_lower)
        
        ai_likelihood = min(1.0, (formal_score * 0.15) - (casual_score * 0.1))
        return max(0.0, min(1.0, ai_likelihood))
    
    return 0.45 if len(text) % 2 == 0 else 0.55

WEIGHTS = {"groq": 0.6, "stylometry": 0.4}

LABEL_HIGH_AI = "High-confidence AI-generated: This content is very likely generated by AI (confidence: 90%+). If you are the creator and believe this is incorrect, you may file an appeal."
LABEL_HIGH_HUMAN = "High-confidence human-written: This content appears to be written by a human (confidence: 90%+). If you are the creator and believe this is incorrect, you may file an appeal."
LABEL_UNCERTAIN = "Uncertain attribution: The system is uncertain whether this content was written by a human or generated by AI (confidence: 50%–90%). Creator appeals are available."

def compute_combined_score(groq_score, stylo_score):
    final = WEIGHTS["groq"] * groq_score + WEIGHTS["stylometry"] * stylo_score
    # conflict rule: if signals differ a lot and final in warning range, downgrade to uncertain
    if abs(groq_score - stylo_score) >= 0.25 and 0.6 <= final < 0.9:
        # map to uncertain by returning a mid value
        return final, "uncertain"
    if final >= 0.9:
        return final, "ai"
    if final <= 0.1:
        return final, "human"
    return final, "uncertain"

def persist_audit(content_id, creator_id, result, confidence, signals, label_text, notes=""):
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute(
        "INSERT INTO audit (timestamp, content_id, creator_id, result, confidence, signals_json, label_text, notes) VALUES (?,?,?,?,?,?,?,?)",
        (datetime.utcnow().isoformat() + "Z", content_id, creator_id, result, confidence, json.dumps(signals), label_text, notes),
    )
    conn.commit()
    rowid = c.lastrowid
    conn.close()
    return rowid

@app.route("/", methods=["GET"])
def index():
    return """
    <h1>Provenance Guard</h1>
    <p>Choose an endpoint:</p>
    <ul>
      <li><a href="/submit">Submit content</a></li>
      <li><a href="/log">View audit log</a></li>
      <li><a href="/appeal">File an appeal</a></li>
    </ul>
    """


@app.route("/submit", methods=["GET", "POST"])
@limiter.limit("30 per hour", key_func=creator_key)
def submit():
    if request.method == "GET":
        return """
        <h2>Submit content</h2>
        <form method="post" action="/submit">
          <label>Content ID</label><br>
          <input name="content_id" required><br><br>
          <label>Creator ID</label><br>
          <input name="creator_id"><br><br>
          <label>Text</label><br>
          <textarea name="text" rows="6" cols="60" required></textarea><br><br>
          <button type="submit">Submit</button>
        </form>
        """

    data = get_request_data()
    content_id = data.get("content_id")
    text = data.get("text", "")
    creator_id = data.get("creator_id")
    if not content_id or not text:
        return jsonify({"error": "content_id and text required"}), 400

    stylo = compute_stylometry_score(text)
    groq = call_groq_stub(text)
    final_score, category = compute_combined_score(groq, stylo)

    if category == "ai":
        label = LABEL_HIGH_AI
    elif category == "human":
        label = LABEL_HIGH_HUMAN
    else:
        label = LABEL_UNCERTAIN

    signals = {"groq": groq, "stylometry": stylo}
    notes = "Computed by backend"
    audit_id = persist_audit(content_id, creator_id, category, final_score, signals, label, notes)

    return jsonify({
        "content_id": content_id,
        "result": category,
        "confidence": round(final_score, 4),
        "label": label,
        "audit_id": audit_id,
        "signals": {"groq": round(groq, 4), "stylometry": round(stylo, 4)},
    }), 200

@app.route("/log", methods=["GET"])
def get_log():
    content_id = request.args.get("content_id")
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    c = conn.cursor()
    if content_id:
        c.execute("SELECT * FROM audit WHERE content_id = ? ORDER BY id DESC LIMIT 50", (content_id,))
    else:
        c.execute("SELECT * FROM audit ORDER BY id DESC LIMIT 50")
    rows = [dict(r) for r in c.fetchall()]
    conn.close()
    # parse signals_json
    for r in rows:
        try:
            r["signals"] = json.loads(r.get("signals_json") or "{}")
        except Exception:
            r["signals"] = {}
        r.pop("signals_json", None)
    return jsonify(rows)

@app.route("/appeal", methods=["GET", "POST"])
def appeal():
    if request.method == "GET":
        return """
        <h2>File an appeal</h2>
        <form method="post" action="/appeal">
          <label>Content ID</label><br>
          <input name="content_id" required><br><br>
          <label>Creator ID</label><br>
          <input name="creator_id" required><br><br>
          <label>Reason</label><br>
          <textarea name="reason" rows="6" cols="60" required></textarea><br><br>
          <button type="submit">Submit appeal</button>
        </form>
        """

    data = get_request_data()
    content_id = data.get("content_id")
    creator_id = data.get("creator_id")
    reason = data.get("reason", "")
    if not content_id or not creator_id or not reason:
        return jsonify({"error": "content_id, creator_id, and reason required"}), 400

    # link to most recent audit for content if available
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute("SELECT id FROM audit WHERE content_id = ? ORDER BY id DESC LIMIT 1", (content_id,))
    row = c.fetchone()
    linked_audit_id = row[0] if row else None
    c.execute(
        "INSERT INTO appeals (timestamp, content_id, creator_id, reason, status, linked_audit_id) VALUES (?,?,?,?,?,?)",
        (datetime.utcnow().isoformat() + "Z", content_id, creator_id, reason, "under review", linked_audit_id),
    )
    conn.commit()
    appeal_id = c.lastrowid
    # annotate audit notes
    if linked_audit_id:
        c.execute("UPDATE audit SET notes = notes || ? WHERE id = ?", (" | appealed", linked_audit_id))
        conn.commit()
    conn.close()

    return jsonify({"content_id": content_id, "status": "under review", "appeal_id": appeal_id}), 200

if __name__ == "__main__":
    import sys
    port = int(sys.argv[1]) if len(sys.argv) > 1 else int(os.environ.get("PORT", "5000"))
    app.run(host="0.0.0.0", port=port, debug=True)
